-- EXPLORATORY DATA ANALYSIS (EDA) --

-------------------------------------------------------------------------------------------------
-- 1. Database Exploration

-- Explore all tables in the database
select * from Information_Schema.Tables;


-- Explore all columns in the database
select * from Information_Schema.Columns
where table_name = 'dim_customers';

select * from Information_Schema.Columns
where table_name = 'dim_products';

select * from Information_Schema.Columns
where table_name = 'fact_sales';

--------------------------------------------------------------------------------------------------------

-- 2. Dimension Exploration

-- Explore all countries of customers
select distinct country
from gold.dim_customers;

-- Explore all categories of product
select distinct category, subcategory, product_name
from gold.dim_products
order by 1,2,3;

--------------------------------------------------------------------------------------------------------

-- 3. Date Exploration

-- order date, min/max order date, range of order
select 
	min(order_date), 
	max(order_date),
	(max(order_date)-min(order_date))/365 order_range_years,
	max(order_date)-min(order_date) order_range_days
from gold.fact_sales;

-- youngest and oldest customer
select 
	min(birthdate) oldest_birthdate,
	max(birthdate) youngest_birthdate,
	(current_date-min(birthdate))/365 younest_age,
	(current_date-max(birthdate))/365 oldest_age,
	(max(birthdate)-min(birthdate))/365 age_gap_years,
	max(birthdate)-min(birthdate) age_gap_days
from gold.dim_customers;


--------------------------------------------------------------------------------------------------------

-- 4. Measures Exploration

-- Total Sales
select sum(sales_amount) total_sales
from gold.fact_sales;

-- no. of items sold
select sum(quantity) total_quantity
from gold.fact_sales;

-- avg. selling price
select avg(price) average_selling_price
from gold.fact_sales; 

-- total no. of orders 
select count(distinct order_number) total_no_of_orders
from gold.fact_sales;

-- total no. of products
select count(distinct product_id) total_no_of_products
from gold.dim_products;

-- total no. of customer
select count(distinct customer_id) total_no_of_customers
from gold.dim_customers;

-- total no. of customer who placed order
select count(distinct customer_key) total_no_of_customers_who_ordered
from gold.fact_sales;



-- REPORT of Measures Exploration

select 'Total Sales' measure_name, sum(sales_amount) measure_value from gold.fact_sales
union all
select 'Total Quantity', sum(quantity) from gold.fact_sales
union all
select 'Average Price', avg(price)  from gold.fact_sales 
union all
select 'Total Order', count(distinct order_number) from gold.fact_sales
union all
select 'Total Products', count(distinct product_id) from gold.dim_products
union all
select 'Total Customers', count(distinct customer_id) from gold.dim_customers
union all
select 'Total Customers who ordered', count(distinct customer_key) 
from gold.fact_sales;


--------------------------------------------------------------------------------------------------------



-- 5. Magnitude

-- Total customers by countries
select country, count(*) total_customers
from gold.dim_customers
group by country
order by total_customers desc;

-- Total customers by gender
select gender, count(*) total_person
from gold.dim_customers
group by gender
order by total_person desc;

-- Total product by category
select category, count(*) total_product
from gold.dim_products
group by category
order by total_product desc;

-- Average cost in each category
select category, avg(cost) average_cost
from gold.dim_products
group by category
order by average_cost desc;

-- Total revenue generated for each category
select dp.category, sum(fs.sales_amount) total_revenue
from gold.fact_sales fs
join gold.dim_products dp
	on fs.product_key = dp.product_key
group by dp.category
order by total_revenue desc;

-- Total revenue generated by each customer
select dp.customer_id, dp.first_name, dp.last_name, sum(fs.sales_amount) total_revenue
from gold.fact_sales fs
join gold.dim_customers dp
	on fs.customer_key = dp.customer_key
group by dp.customer_id, dp.first_name, dp.last_name
order by total_revenue desc;

-- Distribution of items sold across countries
select dp.country, sum(fs.quantity) total_items
from gold.fact_sales fs
join gold.dim_customers dp
	on fs.customer_key = dp.customer_key
group by dp.country
order by total_items desc;

--------------------------------------------------------------------------------------------------------


-- 6. Ranking Analysis


-- 5 product with highest revenue
-- 2 ways for next 2 question, 1. window fn, 2. limit
select *
from (
	select 
		dp.product_name, 
		sum(fs.sales_amount) total_revenue,
		row_number() over(order by sum(fs.sales_amount) desc) rank_p
	from gold.fact_sales fs
	join gold.dim_products dp
		on fs.product_key = dp.product_key
	group by dp.product_name
) t
where t.rank_p <=5;

-- 5 product with lowest revenue
select dp.product_name, sum(fs.sales_amount) total_revenue
from gold.fact_sales fs
join gold.dim_products dp
	on fs.product_key = dp.product_key
group by dp.product_name
order by total_revenue
limit 5;

-- top 10 customer who have generated highest revenue
select *
from (
	select 
		dp.customer_id, dp.first_name, dp.last_name, 
		sum(fs.sales_amount) total_revenue,
		row_number() over(order by sum(fs.sales_amount) desc) rank_p
	from gold.fact_sales fs
	join gold.dim_customers dp
		on fs.customer_key = dp.customer_key
	group by dp.customer_id, dp.first_name, dp.last_name
) t
where t.rank_p <=10;

-- 3 customer who have generated lowest orders
select *
from (
	select 
		dp.customer_id, dp.first_name, dp.last_name, 
		count(distinct fs.order_number) total_orders,
		row_number() over(order by count(distinct fs.order_number)) rank_p
	from gold.fact_sales fs
	join gold.dim_customers dp
		on fs.customer_key = dp.customer_key
	group by dp.customer_id, dp.first_name, dp.last_name
) t
where t.rank_p <=3;

